name: ci

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
  # services:
  #   dynamodb:
  #     image: amazon/dynamodb-local
  #     ports:
  #       - 8000:8000
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo:  true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            www.google.com:443
            github.com:443
            pypi.org:443

      - name: Check-Out
        uses: actions/checkout@v4

      - run:  pipx install poetry~=1.8.0
        name: Install Poetry

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # => Used in our Î»s
          cache: poetry

      - run:  poetry install
        name: Install Requirements

      - run:  poetry run pytest test/unit
        name: Unit-Tests

#     - {...}
#   {...}
# {...}
